---
# vars file for Ubuntu

# yamllint disable-line rule:line-length
irods_package_extension: "{{ '' if irods_version is none else '=' + irods_version }}"
# yamllint disable-line rule:line-length
irods_server_pkgname: "irods-server{{ irods_package_extension }}"
irods_server_pkgname_short: "irods-server"
# To force an specific version
# and avoid error "unmet dependencies"
# (Depends: irods-runtime (= 4.2.9) but 4.2.10 is to be installed)
# we have to specify dependencies version
# yamllint disable-line rule:line-length
irods_runtime_pkgname: "irods-runtime{{ irods_package_extension }}"
irods_runtime_pkgname_short: "irods-runtime"
# yamllint disable-line rule:line-length
irods_icommands_pkgname: "irods-icommands{{ irods_package_extension }}"
irods_icommands_pkgname_short: "irods-icommands"
# yamllint disable-line rule:line-length
irods_database_pkgname: "irods-database-plugin-postgres{{ irods_package_extension }}"
irods_database_pkgname_short: "irods-database-plugin-postgres"
#FIXME automatically determine the major version A.B but without the minor version
irods_s3_plugin_pkgname: "irods-resource-plugin-s3=5.0*"
irods_s3_plugin_pkgname_short: "irods-resource-plugin-s3"

